### ISSUE TITLE
Dynamoose schema is not parsed correctly

### ISSUE THREAD

**Issue by japier** [yoitsro/joigoose#23] opened 2018-08-20 07:25 UTC
Hi guys, 
I tried to use the joigoose with dynamoose but when I try to convert the schema generated by, dynamoose keep sending the same error `Validation failed: `

Here's my test

````
const dynamoose = require('dynamoose');
const joigoose = require('joigoose');
const Joi = require('joi');

dynamoose.local('http://localhost:8083');

dynamoose.AWS.config.update({
  accessKeyId: 'secret',
  secretAccessKey: 'secret',
  region: 'us-east-1',
});

dynamoose.setDefaults({
  create: true,
});

const schema = Joi.object().keys({
  id: Joi.string().required(),
  status: Joi.string(),
});

const entrySchema = joigoose(dynamoose).convert(schema);
const EntryModel = dynamoose.model('Entry', entrySchema);

const entry1 = new EntryModel({ id: 'someId', status: 'status-one'});
entry1.save(e => {
  if (e) {
    console.log('some error: ', e);
  } else {
    console.log('no error');
  }
````

and sends this as output, 
```
$ node index.js
some error:  { ValidationError: Validation failed: id
    at Attribute.toDynamo (/Users/javiercastro/Documents/projects/ex/joigoose/node_modules/dynamoose/lib/Attribute.js:352:11)
    at Schema.toDynamo (/Users/javiercastro/Documents/projects/ex/joigoose/node_modules/dynamoose/lib/Schema.js:162:25)
    at NewModel.Model.put (/Users/javiercastro/Documents/projects/ex/joigoose/node_modules/dynamoose/lib/Model.js:286:20)
    at Object.<anonymous> (/Users/javiercastro/Documents/projects/ex/joigoose/index.js:26:8)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12) name: 'ValidationError', message: 'Validation failed: id' }
✨  Done in 0.31s.
```

but if I did the same with pure dynamoose validation it works
code
```
const dynamoose = require('dynamoose'), Schema = dynamoose.Schema;

// Configuration to dynamoose local
dynamoose.local('http://localhost:8083');

dynamoose.AWS.config.update({
  accessKeyId: 'secret',
  secretAccessKey: 'secret',
  region: 'us-east-1',
});

dynamoose.setDefaults({
  create: true,
});

const schema = new Schema({
  id: {
    type: String,
    required: true
  },
  status: {
    type: String
  }
});
const EntryModel = dynamoose.model('Entry', schema);

const entry1 = new EntryModel({ id: 'someId', status: 'status-one'});
entry1.save(e => {
  if (e) {
    console.log('some error: ', e);
  } else {
    console.log('no error');
  }
}); 
```
output
```
$ node index.js
no error
✨  Done in 0.34s.
```

even the validation works if I don't specify an Id
```
some error:  { ValidationError: Required value missing: id
    at Attribute.toDynamo (/Users/javiercastro/Documents/projects/ex/joigoose/node_modules/dynamoose/lib/Attribute.js:337:13)
    at Schema.toDynamo (/Users/javiercastro/Documents/projects/ex/joigoose/node_modules/dynamoose/lib/Schema.js:162:25)
    at NewModel.Model.put (/Users/javiercastro/Documents/projects/ex/joigoose/node_modules/dynamoose/lib/Model.js:286:20)
    at Object.<anonymous> (/Users/javiercastro/Documents/projects/ex/joigoose/index.js:38:8)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
  name: 'ValidationError',
  message: 'Required value missing: id' }
```

thanks

**Comment by yoitsro** [comment] 2018-08-20 12:51
Hi @japier. Thanks for raising the issue.

Joigoose was never designed to work with dynagoose, but in this case, it should generally work.

Please can you log what the output of `entrySchema` is and paste it here?

**Comment by japier** [comment] 2018-08-21 03:03
Hi @yoitsro sure, 
how do I get the entry schema, do you mean the output once it converted?

**Comment by yoitsro** [comment] 2018-08-21 08:58
Yes please. Either a `console.log` of the actual object or a stringified version of it.

**Comment by japier** [comment] 2018-08-21 10:35
Sure
```
{ id:
   { validate: { isAsync: true, validator: [AsyncFunction: bound ] },
     required: true,
     type: [Function: String] },
  status:
   { validate: { isAsync: true, validator: [AsyncFunction: bound ] },
     type: [Function: String] } }
```

**Comment by yoitsro** [comment] 2018-08-21 11:03
The reason that this is happening is because Joigoose was designed to work with Mongoose, which supports async validators. According to https://github.com/dynamoosejs/dynamoose/issues/313 Dynamoose doesn't support async validators yet.

I've left a comment on that issue to try to ensure that their API is the same as mongoose's so that Joigoose will be compatible.

Closing for now until https://github.com/dynamoosejs/dynamoose/issues/313 is closed. Feel free to open a new issue after that if it's still not working and the APIs are the same.

**Closed by yoitsro** 2018-08-21 11:03 UTC
