### ISSUE TITLE
Optional objects with required properties are not working as expected

### ISSUE THREAD

**Issue by victorperin** [yoitsro/joigoose#25] opened 2019-01-30 15:56 UTC
Example:
```js
const Joi = require('joi')
const mongoose = require('mongoose')
const joigoose = require('joigoose')
const Joigoose = joigoose(mongoose)

const joiObject = Joi.object().keys({
  optional: Joi.object().keys({
    requiredProperty: Joi.string().required()
  }),
  otherProperty: Joi.string().required()
})

const Model = mongoose.model('course',  Joigoose.convert(joiObject) )

const objectToBeValidated = {
  // optional: { requiredProperty: 'test' },
  otherProperty: 'test'
};

joiObject.validate(objectToBeValidated); // works fine
( new Model(objectToBeValidated) ).validate(); // throw validation error
```

Expected result: `should be a valid object`.

PS: thanks for the lib, it's awesome! :smile:

**Comment by yoitsro** [comment] 2019-01-30 16:07
Hey! What is the specific error is it throwing?

**Comment by victorperin** [comment] 2019-01-30 16:28
It throws:
```
ValidationError: course validation failed: optional.requiredProperty: Path `optional.requiredProperty` is required.
```

**Comment by yoitsro** [comment] 2019-01-30 16:32
Can you try and explicitly set `.optional()` to the `optional` key?

```
const joiObject = Joi.object().keys({
  optional: Joi.object().keys({
    requiredProperty: Joi.string().required()
  }).optional(),
  otherProperty: Joi.string().required()
})
```

**Comment by victorperin** [comment] 2019-01-30 17:02
It still reproduce the same error.

**Comment by yoitsro** [comment] 2019-01-30 18:41
I can see the error myself locally and I can see the cause of the error, but it's quite a large change required to get it working properly and I don't have much time at the moment. If you'd be interesting in working on it, I can spend a little bit of time explaining the issue to you if necessary?

**Comment by victorperin** [comment] 2019-01-30 19:35
I can look this weekend.
I think I just need an info in how the lib works internaly. From that, I think I can fix. :smile:

**Comment by yoitsro** [comment] 2020-02-19 14:17
Closing this, but I'll reopen if necessary.

**Closed by yoitsro** 2020-02-19 14:17 UTC

**Comment by FullmetalBober** [comment] 2024-04-17 12:45
#73 here my simple trick for such validation
